version: '3.8'

services:
  axolotl-train-rahmat:
    build: .
    container_name: qwen3-finetune-rahmat
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0,1,2,3
      - HF_HOME=/workspace/.cache/huggingface
      - WANDB_DIR=/workspace/logs
      - TOKENIZERS_PARALLELISM=false
      - NCCL_DEBUG=INFO
      - NCCL_IB_DISABLE=0
      - NCCL_P2P_DISABLE=0
      - OMP_NUM_THREADS=8
    volumes:
      # Mount the entire project directory (this includes all subdirectories)
      - .:/workspace
    working_dir: /workspace
    command: bash scripts/train.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    restart: unless-stopped
    tty: true
    stdin_open: true